logging:
  level:
    dejay.rnd: DEBUG

server:
  servlet:
    encoding:
      force: 'true'
      charset: UTF-8
  port: '8080'
  tomcat:
    max-threads: '500'


spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
      enabled: 'true'
      file-size-threshold: 2KB
  mvc:
    converters:
      preferred-json-mapper: gson
  datasource:
    password: tkatjd1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://192.168.1.242:13306/billy?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul


jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  #token-validity-in-seconds: 86400
  access-token-validity-in-seconds: 1800 # 초 단위
  refresh-token-validity-in-seconds: 604800
